remote_theme: just-the-docs/just-the-docs
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
color_scheme: dark

docs_list_title: roachslimes Docs
docs:

- title: Introduction
  url: readme.md

- title: Assembly
  url: Assembly.md
